background {
  monitor =
  path = ~/Pictures/purple-glow-3840x1080.png
  blur_passes = 2
  blur_size = 8
  noise = 0.02
  vibrancy = 0.2
}

general {
  hide_cursor = true
  grace = 0
}

label {
  monitor =
  text = $TIME
  font_size = 72
  font_family = JetBrainsMono Nerd Font
  color = rgba(236, 229, 247, 1.0)
  position = 0, 120
  halign = center
  valign = center
}

label {
  monitor =
  text = hi $USER
  font_size = 18
  font_family = JetBrainsMono Nerd Font
  color = rgba(201, 166, 255, 1.0)
  position = 0, 40
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 280, 48
  rounding = 16
  outer_color = rgba(91, 12, 166, 1.0)
  inner_color = rgba(14, 7, 22, 0.9)
  font_color = rgba(236, 229, 247, 1.0)
  outline_thickness = 2
  placeholder_text = <i>password…</i>
  position = 0, -120
  halign = center
  valign = center
  check_color = rgba(139, 47, 224, 1.0)
  fail_color = rgba(255, 85, 119, 1.0)
}
